name: deploy-server
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "packages/server/**"
      - ".github/workflows/deploy-server.yml"
jobs:
  build-deploy-server:
    runs-on: ubuntu-latest
    steps:
      - name: Clone and checkout.
        uses: actions/checkout@v2

      - name: Deploying server to Heroku.
        shell: bash
        env:
          HEROKU_SSH_KEY: ${{ secrets.HEROKU_SSH_KEY }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< "$HEROKU_SSH_KEY"
          git remote add heroku ssh://git@heroku.com/got-battles-server.git
          git push heroku `git subtree split --prefix=packages/server master`:master --force
