name: deploy-server
on:
  push:
    branches:
      - "master"
    paths:
      - "packages/server/**"
      - ".github/workflows/deploy-server.yml"
jobs:
  build-deploy-server:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH client and start ssh-agent.
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.HEROKU_SSH_KEY }}

      - name: Clone and checkout.
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Installing Yarn.
        run: curl -o- -L https://yarnpkg.com/install.sh | bash
        shell: bash

      - name: Deploying server to Heroku.
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_REMOTE: ${{ secrets.HEROKU_REMOTE }}
        run: |
          git remote add heroku "$HEROKU_REMOTE"
          yarn heroku-push master

